### ISSUE TITLE
Cannot import-module for use

### ISSUE THREAD

**Issue by Reactor46** [AsBuiltReport/AsBuiltReport.NetApp.ONTAP#3]
**Describe the bug**

**To Reproduce**
1. Open Powershell console or ISE
2. Import-Module .\AsBuiltReport.NetApp.ONTAP-0.3.0\AsBuiltReport.NetApp.ONTAP.psm1
3. See error:
D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\AsBuiltReport.NetApp.ONTAP.psm1 : Failed to import function 

**Expected behavior**
Import-Module should import the module for standard use.

**Screenshots**
Import-Module .\AsBuiltReport.NetApp.ONTAP-0.3.0\AsBuiltReport.NetApp.ONTAP.psm1
D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\AsBuiltReport.NetApp.ONTAP.psm1 : Failed to import function D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1: At 
D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:36 char:97
+ ...  'Status' = if ($Item.OpStatus) {$Item.OpStatus.ToString().ToUpper()}
+                                                                          ~
The hash literal was incomplete.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:37 char:29
+                             'Data Protocols' = $Item.DataProtocols
+                             ~~~~~~~~~~~~~~~~
Unexpected token ''Data Protocols'' in expression or statement.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:1 char:34
+ function Get-AbrOntapNetworkMgmt {
+                                  ~
Missing closing '}' in statement block or type definition.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:68 char:93
+ ...  'Status' = if ($Item.OpStatus) {$Item.OpStatus.ToString().ToUpper()}
+                                                                          ~
The hash literal was incomplete.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:69 char:25
+                         'Data Protocols' = $Item.DataProtocols
+                         ~~~~~~~~~~~~~~~~
Unexpected token ''Data Protocols'' in expression or statement.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:89 char:9
+         }
+         ~
Unexpected token '}' in expression or statement.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:100 char:97
+ ...  'Status' = if ($Item.OpStatus) {$Item.OpStatus.ToString().ToUpper()}
+                                                                          ~
The hash literal was incomplete.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:101 char:29
+                             'Data Protocols' = $Item.DataProtocols
+                             ~~~~~~~~~~~~~~~~
Unexpected token ''Data Protocols'' in expression or statement.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:122 char:9
+         }
+         ~
Unexpected token '}' in expression or statement.
At D:\GIT_REPO\AsBuiltReport.NetApp.ONTAP-0.3.0\Src\Private\Get-AbrOntapNetworkMGMT.ps1:132 char:93
+ ...  'Status' = if ($Item.OpStatus) {$Item.OpStatus.ToString().ToUpper()}
+                                                                          ~
The hash literal was incomplete.
Not all parse errors were reported.  Correct the reported errors and try again.
At line:1 char:1
+ Import-Module .\AsBuiltReport.NetApp.ONTAP-0.3.0\AsBuiltReport.NetApp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,AsBuiltReport.NetApp.ONTAP.psm1

**Desktop (please complete the following information):**
 - OS: Windows 10 (^$bit)
 - PS 5.1

**Comment by tpcarman** [comment]
@Reactor46 You either need to add `D:\GIT_REPO` to $env:PSModulePath` or extract the NetApp ONTAP module to one of the folders already in `$env:PSModulePath`. The module folder name should also be `AsBuiltReport.NetApp.ONTAP`.

**Comment by rebelinux** [comment]
Hello @Reactor46,

Could you test with the most recent version 0.4.0?

What is your powershell version? $PSVersionTable

**Comment by Reactor46** [comment]
Works with .0.4.0 now!

Name                           Value                                                                                                                                                                                                                             
----                           -----                                                                                                                                                                                                                             
PSVersion                      5.1.17763.2090                                                                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                           
BuildVersion                   10.0.17763.2090                                                                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                               
SerializationVersion           1.1.0.1

**Comment by rebelinux** [comment]
The report is in constant development, if you have any recommendations they will be well received.
