### ISSUE TITLE
A parameter issue is showing about HTTPS error

### ISSUE THREAD

**Issue by JGANetapp** [AsBuiltReport/AsBuiltReport.NetApp.ONTAP#35]
While running the command in generating the asbuilt report I got this one.

![Screenshot 2023-08-04 131625](https://github.com/AsBuiltReport/AsBuiltReport.NetApp.ONTAP/assets/141596871/1b95b2b4-2e90-4346-ac27-dcadb003fca3)

Can anyone help me how to solve this issue?

**Comment by rebelinux** [comment]
Wha version of Ontap are you using?

**Comment by JGANetapp** [comment]
> 

I am using Ontap 9.12

**Comment by rebelinux** [comment]
Unfortunately, I don't have access to Ontap 9.11+ versions to be able to carry out the tests.

**Comment by varunrai** [comment]
It seems to be a compatibility issue between 9.13.x and 9.12.x ONTAP dependencies.

Connect-NcController does not seem to accept the parameter -HTTPS in 9.13.x.
https://github.com/AsBuiltReport/AsBuiltReport.NetApp.ONTAP/blob/fbac2a937e2a6fce2b402eb9ad93d9085b2647bb/Src/Public/Invoke-AsBuiltReport.NetApp.ONTAP.ps1#L61C3-L61C3

The workaround is to uninstall the powershell module NetApp.ONTAP from 9.13.x and install 9.12.x which seems to be working fine.

**Comment by rebelinux** [comment]
Removed the -HTTPS from the connection code. Please update to v0.6.6 and test it again.

Update-Module -Name AsBuiltReport.NetApp.ONTAP -Force
