### ISSUE TITLE
Add metrocluster FC support

### ISSUE THREAD

**Issue by MicKBfr** [AsBuiltReport/AsBuiltReport.NetApp.ONTAP#40]
### Description

Hello, it will be great to add somme option like auto vserver parsing on metrocluster to remove information with vserver ending by -mc 

### Additional Context

in metrocluster FMCC  we have vserver with name ending by -mc that are normaly stopped

with an new option we can try to autoremove vserver with -mc information.
perhaps we can use the $Options.Exclude.Vserver and add -mc vserver automatically

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.NetApp.ONTAP/issues) before submitting this change request.

**Comment by MicKBfr** [comment]
I can help, but i just want to have some guideline (how to add a new option ?) to avoid breaking all the project

**Comment by rebelinux** [comment]
Hello,

You need to edit the json template file:

https://github.com/AsBuiltReport/AsBuiltReport.NetApp.ONTAP/blob/dev/AsBuiltReport.NetApp.ONTAP.json

Something like this:

![Screenshot_20240731_160836_Chrome~2](https://github.com/user-attachments/assets/877625a4-7a4c-4f40-adbe-be04026ee3f4)

Also is needed to modify the filter logic in the report source code.

**Comment by rebelinux** [comment]
Any update on this?

**Comment by MicKBfr** [comment]
Hello, yes i will made a new pull request on next days
thanks

**Comment by rebelinux** [comment]
A new version has been released with the changes you introduced and other new features such as NVME support. If you are able to test it and let me know the results I would greatly appreciate it.

**Comment by MicKBfr** [comment]
hello,
i have test new version successfully.
just in release note, it's a vserver filter with -mc not volume

we have some little issue with efficiency. I will try to fix it and made a new pull request
thanks

**Comment by rebelinux** [comment]
Don't forget to sync the changes to your branch repo before making any changes back to upstream.

![image](https://github.com/user-attachments/assets/43ef1470-91fb-4526-a56e-2d2996705faa)
